name: Security Checks
on: [push, pull_request]

jobs:
  sonarcloud-test:
    name: Sonarcloud Security Tests
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            ref: master
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        - name: Check SonarCloud Quality Gate
          run: |
            QG_STATUS=$(curl https://sonarcloud.io/api/qualitygates/project_status\?projectKey\=maiglesias_NodeGoat | jq -r '.projectStatus.status')
            if [ ${QG_STATUS} == "ERROR" ]; then
                echo "Quality Gate failed. Stopping the pipeline."
                exit 1
            fi
  security-tests:
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build and Launch Docker Node-Goat Image
        run: |
          docker-compose build
          docker-compose up --detach

      - name: Snyk Test
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=high

      - name: Upload results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:4000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

    