name: Security Checks
on: [push, pull_request]

jobs:
  build:
    name: SECURITY CHECK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Building Docker Node-Goat Image
        run: docker-compose build
      - name: Launching the app
        run: docker-compose up --detach
           - name: Checkout code
        uses: actions/checkout@v2

      - name: Start ZAP container
        run: docker run -v $(pwd)/zap:/zap/wrk/:rw -t owasp/zap2docker-weekly zap.sh -daemon -config api.disablekey=true

      - name: Run ZAP scan
        run: docker run --network host -v $(pwd)/zap:/zap/wrk/:rw owasp/zap2docker-weekly zap-baseline.py -t http://localhost:4000 -g gen.conf -r report.html

      - name: Stop ZAP container
        run: docker run --network host -t owasp/zap2docker-weekly zap.sh -s shutdown

      - name: Upload ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap/wrk/

  sonarcloud-test:
    name: SONARCLOUD CHECK
    runs-on: ubuntu-latest

    steps:
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check SonarCloud Quality Gate
        run: |
          QG_STATUS=$(curl https://sonarcloud.io/api/qualitygates/project_status\?projectKey\=maiglesias_NodeGoat | jq -r '.projectStatus.status')

          if [ ${QG_STATUS} == "ERROR" ]; then
              echo "Quality Gate failed. Stopping the pipeline."
              exit 1
          fi
 
