name: Security Checks
on: [push, pull_request]

jobs:
  test:
    name: SECURITY CHECK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Building Docker Node-Goat Image
        run: docker-compose build
      - name: Launching the app
        run: docker-compose up --detach

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      - name: Check SonarCloud Quality Gate
        run: |
          TASK_ID=$(curl -s -u "${{ secrets.SONARCLOUD_TOKEN }}:" "https://sonarcloud.io/api/ce/activity" | jq -r '.[0].analysisId')
          QG_STATUS=$(curl -s -u "${{ secrets.SONARCLOUD_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?analysisId=${TASK_ID}" | jq -r '.projectStatus.status')

          if [ "${QG_STATUS}" = "ERROR" ]; then
              echo "Quality Gate failed. Stopping the pipeline."
              exit 1
          fi

          
          curl -s -u "a121f9c444947687c9b2afbc49c9974a1220ffe2:" "https://sonarcloud.io/api/ce/activity" | jq -r '.[0].analysisId'