name: Security Checks
on: [push, pull_request]

jobs:
  test:
    name: SECURITY CHECK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Building Docker Node-Goat Image
        run: docker-compose build
      - name: Launching the app
        run: docker-compose up --detach

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      - name: Check SonarCloud Quality Gate
        run: |
          QG_STATUS=$(curl https://sonarcloud.io/api/qualitygates/project_status\?projectKey\=maiglesias_NodeGoat | jq -r '.projectStatus.status')

          if [ ${QG_STATUS} == "ERROR" ]; then
              echo "Quality Gate failed. Stopping the pipeline."
              exit 1
          fi
